### ISSUE TITLE
Add Detailed Screen To App and booking functionality

### ISSUE THREAD

**Issue by sahil-patel6** [theblazecoders/smart-car-parking#42] opened 2019-04-08 17:54 UTC

**Comment by HarshKhandeparkar** [comment] 2019-04-08 17:54
Please add some description

**Comment by sahil-patel6** [comment] 2019-04-08 17:56
Don't worry. There is no need btw I am only going to do so no need

**Comment by sahil-patel6** [comment] 2019-04-08 17:58
this issue will be closed by tomorrow or day after tomorrow

**Comment by HarshKhandeparkar** [comment] 2019-04-08 18:07
Btw, please add `Fixes #issuenumber` to the PR body so that the issue is
closed automatically as soon as the PR is merged. E.g. a PR with `Fixes #1`
in the body will close issue no. 1 upon merging. This keeps a good track of
history. Thanks.

**Comment by sahil-patel6** [comment] 2019-04-08 18:12
Ok I will make note of that

**Closed** 2019-04-12 08:13 UTC
Labels: flutter
